name: xcontext
description: This simple package adds static extension methods and getters to the BuildContext context object from the widgets, material, and cupertino libraries.
version: 0.1.0+1
homepage: https://github.com/dartsidedev/xcontext
issue_tracker: https://github.com/dartsidedev/xcontext/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
