name: Continuous Integration

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Verify source code is formatted
        run: flutter format --set-exit-if-changed .
      - name: Verify there are no analyzer errors
        run: flutter analyze --fatal-infos --fatal-warnings .
      - name: Verify all tests pass
        run: flutter test --coverage

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [check]
    if: github.ref == 'refs/heads/master'
    # Continue on error doesn't seem to work?
    # Using || true for publishing
    # continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Dart
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update
          sudo apt-get install dart
          export PATH="$PATH:/usr/lib/dart/bin"
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          echo ${{ secrets.PUB_CREDENTIALS_JSON }} > ~/.pub-cache/credentials.json
      - name: Publish the package
        run: |
          export version=v$(grep "version: " pubspec.yaml | cut -c 10-)
          dart pub publish --force && (git tag $version && git push origin $version && gh release create $version) || true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Delete credentials
        run: rm ~/.pub-cache/credentials.json
